# Generated by Django 3.2.8 on 2021-10-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500, unique=True)),
                ('pubdate', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('feeder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.parser')),
            ],
        ),
    ]
