# Generated by Django 3.2.8 on 2021-10-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_parseddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
