# Generated by Django 3.2.8 on 2021-10-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_parseddata_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
