# Generated by Django 3.2.8 on 2021-11-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_searchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrecord',
            name='ip',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
