# Generated by Django 3.2.8 on 2021-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_slideshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
