# Generated by Django 3.2.8 on 2021-11-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_informaion'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='ic_color',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
