# Generated by Django 3.2.8 on 2021-11-04 10:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_parser_ic_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='ic_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
