# Generated by Django 3.2.8 on 2021-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='position',
            field=models.CharField(choices=[('lsh', 'Left SideBar Top'), ('rst', 'Right Sidebar Top')], default='lsh', max_length=500),
        ),
    ]
