# Generated by Django 3.2.8 on 2021-11-04 16:34

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('feed', '0020_alter_blocks_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExSite',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.site', verbose_name='site')),
                ('site_meta', models.CharField(max_length=256)),
                ('site_description', models.TextField(max_length=500)),
                ('site_meta_tag', models.CharField(max_length=255)),
                ('site_favicon', models.ImageField(upload_to='site_image')),
                ('site_logo', models.ImageField(upload_to='site_image')),
                ('slogan', models.CharField(default='Multitasking Living Machine', max_length=150)),
                ('og_image', models.ImageField(upload_to='site_image')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('last_degree', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=120)),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('email_host', models.CharField(max_length=256)),
                ('email_port', models.CharField(max_length=256)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_pass', models.CharField(max_length=256)),
                ('pagination_para', models.CharField(default=10, max_length=2)),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
