# Generated by Django 3.2.8 on 2021-11-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_alter_department_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsercategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
