# Generated by Django 3.2.8 on 2021-11-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0025_alter_parsercategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
