# Generated by Django 3.2.8 on 2021-11-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0026_parser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
