# Generated by Django 3.2.8 on 2021-11-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0027_alter_parser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='s_department',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
