# Generated by Django 3.2.8 on 2021-11-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0028_subscriber_s_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='s_department',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
