# Generated by Django 3.2.8 on 2021-11-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0029_alter_subscriber_s_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exsite',
            name='last_degree',
        ),
        migrations.AddField(
            model_name='exsite',
            name='feed_fetch_time',
            field=models.CharField(default=0, help_text='Put 0,6,12,18 like that', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exsite',
            name='newsletter_send_time',
            field=models.CharField(default=0, help_text='Put 0,6,12,18 like that', max_length=2),
            preserve_default=False,
        ),
    ]
